"""

Revision ID: dbb76b1356fd
Revises: 001
Create Date: 2026-03-06 19:24:39.724463+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbb76b1356fd'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if index already exists before creating
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('hello_world')
    index_names = [idx['name'] for idx in indexes]
    
    if 'ix_hello_world_id' not in index_names:
        op.create_index(op.f('ix_hello_world_id'), 'hello_world', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hello_world_id'), table_name='hello_world')
    # ### end Alembic commands ###
